---
- name: Install Docker Deamon
  hosts: homelab
  vars:
    docker_daemon_options:
      log-driver: "local"
      log-opts:
        max-size: "10m"
        max-file: "3"

    docker_users:
      - "{{ansible_user}}"

  tasks:
    - name: Check Docker version
      ansible.builtin.command: docker --version
      changed_when: false

  roles:
    - role: geerlingguy.docker
      become: true
